// GENERATED by scripts/build-region-maps.mjs — do not edit by hand.
// Regenerate (needs network, hits the EPA and EEA map services): npm run maps:build
//
// The drawn size of each region's map (public/maps/<id>.svg), so the page can
// reserve exactly the right box for it and nothing shifts when the file lands.
export const REGION_MAP_SIZES: Record<string, { w: number; h: number }> = {
  "mid-atlantic": { w: 640, h: 615 },
  "pnw": { w: 640, h: 768 },
  "ca-south-coast": { w: 640, h: 551 },
  "florida-central": { w: 640, h: 353 },
  "florida-south": { w: 640, h: 740 },
  "france-atlantic": { w: 640, h: 745 },
  "france-continental": { w: 640, h: 768 },
  "france-mediterranean": { w: 640, h: 385 },
  "france-alpine": { w: 640, h: 768 },
};
